# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.4
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: cordesir@gmail.com
author_name: Corey Stedman
contract_name: algofire
preset_name: production
project_name: AlgoFire-contracts

